# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'video.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5.QtWidgets import QApplication, QFileDialog, QHBoxLayout, QLabel, QPushButton, QSizePolicy, QSlider, QStyle, QVBoxLayout, QWidget, QStatusBar

from PyQt5 import QtCore, QtGui, QtWidgets, QtMultimedia
from PyQt5.QtWidgets import QFileDialog

file = ""

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Play = QtWidgets.QPushButton(self.centralwidget)
        self.Play.setGeometry(QtCore.QRect(20, 550, 100, 32))
        self.Play.setObjectName("Play")
        self.widget = QVideoWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(20, 10, 751, 521))
        self.widget.setStyleSheet("background color: black")
        self.widget.setObjectName("widget")
        self.OpenFile = QtWidgets.QPushButton(self.centralwidget)
        self.OpenFile.setGeometry(QtCore.QRect(130, 550, 100, 32))
        self.OpenFile.setObjectName("OpenFile")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Play.setText(_translate("MainWindow", "Play"))
        self.OpenFile.setText(_translate("MainWindow", "Open File"))
from PyQt5.QtMultimediaWidgets import QVideoWidget

class Window(QtWidgets.QMainWindow):
    def __init___(self):
        super(Window, self).__init__()
        self.ui = Ui_MainWindow()
        self.ui.setupUi(self)
        self.media = QtMultimedia.QMediaPlayer(self)
        self.media.setVideoOutput (self.ui.video)
        self.ui.Play.clicked.connect (self.Plays)
        self.ui.OpenFile.clicked.connect (self.Open)

    def Open(self):
    file = QFileDialog.getOpenFileName(self, "Выберите видеофайл", ".", "Video Files (*.mp4 *.flv *.ts *.mts *.avi)")
    print (file[0]) 
    if file:
        self.media.setMedia(QMediaContent(QUrl.fromLocalFile (file[0])))
        self.media.play()

    def Plays(self):
        url = QtCore.Qurl(file[0])
        self.media.setMedia (QtMultimedia.QMediaContent (url))
        self.media.play()



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
